### ISSUE TITLE
Icons missing after upgrading to v8.0.0

### ISSUE THREAD

**Issue by benjaminoerskov** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2130]
**What happened**: Icons are missing

**What you expected to happen**: See the icons

**How to reproduce it (as minimally and precisely as possible)**: I Upgraded to v8.0.0.0

**Anything else we need to know?**: Please see attached screenshot. Am I missing something on setup, or is this a bug on the newest version? On the previous package, everything was displaying correctly.

**Environment**:

- .NET Core version: 8
- Healthchecks version: 8.0.0.0
- Operative system: Linux
- Others:
![HealthCheckIconsMissing](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/11537543/50bc1dba-ff38-4b6e-96b8-4fe095d08b39)

**Comment by phivanloi** [comment]
me too.

**Comment by MatheusXavier** [comment]
Same issue here

**Comment by markmonster** [comment]
I can see that loading a font-file fails.

![image](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/1837517/a1e0f11b-ab44-41e5-bfdb-5dfb887c50a9)

**Comment by markmonster** [comment]
Just running the HealthChecks.UI.Sample gives the same reproduction.

Found that the upgrade of css-loader from 4.3.0 to 6.8.1 caused the issue in this PR: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2051

Looks like that the font was inlined in version **4.3.0** till **6.7.4** and published as a separate file the most recent versions of css-loader **6.8.0** and upwards. I'm not a frontend developer, so have no clue what would be the best way to fix this. Rolling back to version 6.7.4 of css-loader sounds like only a temporary solution.

Anyone with a knowledge around webpack / css-loader who can fix this the correct way?

**Comment by chirag-shingala-tark** [comment]
Same issue facing.

**Comment by PatryxCShark** [comment]
Can sb fix it and release new version 8.0.1?

**Comment by dougcunha** [comment]
I've discovered a temporary solution that might be helpful.

To address the issue, you can activate static files handling in your application. Specifically, you'll need to include the file `1ae4e3706fe3f478fcc1.woff2` in the `wwwroot\ui\resources` directory of your project. Here's a snippet of code to illustrate how you can set this up:

```csharp
builder.WebHost.UseWebRoot("wwwroot");

var app = builder.Build();

// This will enable the serving of static files from the specified directory
app.UseStaticFiles();

**Comment by markmonster** [comment]
Where did you get the woff2 file from?

I'm now facing, below error in the temporary solution:
![image](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/1837517/dae95674-e39d-4b31-97ce-2a1ce54b9f92)

**Comment by dougcunha** [comment]
> Where did you get the woff2 file from?
> 
> I'm now facing, below error in the temporary solution: ![image](https://private-user-images.githubusercontent.com/1837517/293093123-dae95674-e39d-4b31-97ce-2a1ce54b9f92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MDc5NTIsIm5iZiI6MTcwMzcwNzY1MiwicGF0aCI6Ii8xODM3NTE3LzI5MzA5MzEyMy1kYWU5NTY3NC1lMzlkLTRiMzEtOTdjZS0yYTFjZTU0YjlmOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMjAwNzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjM0MGNlNjE2MjEwMmQ5Y2VhMWVmYmYyNTIzOTkwYWI1YmYxOWJiNzUzMzk3ZTA4ZmEyNjc2MDgzYzhmNmI0MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rAsZoNXRYcC48KprnuHP2wpOAa4ejodAKXsXwqRAIcM)

I got it from here https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI/assets/fonts/material.woff2

Just rename it to `1ae4e3706fe3f478fcc1.woff2` and you are read to go.

**Comment by PatryxCShark** [comment]
And when I I have REST API application?

**Comment by dougcunha** [comment]
> And when I I have REST API application?

The solution I proposed works just fine with REST API app.

**Comment by MarioDesenv** [comment]
> And when I I have REST API application?

Here, I am still using "startup.cs" from the legacy .net version, so I just created the folders put the file there set the build action to "content" and copy to output to "copy always" and added the "app.UseStaticFiles();" inside the  "Configure(IApplicationBuilder app)". 

Now, all icons working again.
Thanks, @dougcunha!!

**Comment by sesausmd** [comment]
Same error here.
v 8.0.0

**Comment by DeepWorksStudios** [comment]
same issue

**Comment by ceberttylertech** [comment]
I am having this issue too

**Comment by code1line** [comment]
Me too...

**Comment by code1line** [comment]
Please have a look at stackoverflow: [Solution with custom.css-file](https://stackoverflow.com/questions/77696948/healtcheckui-in-net-issues-with-icons/78185081#78185081)

So the above mentioned woff-file is not needed.

**Comment by DefinitelyADev** [comment]
> Please have a look at stackoverflow: [Solution with custom.css-file](https://stackoverflow.com/questions/77696948/healtcheckui-in-net-issues-with-icons/78185081#78185081)
> 
> So the above mentioned woff-file is not needed.

This is a nice temporary solution, but this still should be fixed.

**Comment by burnchar** [comment]
> I've discovered a temporary solution that might be helpful.

Thank you for your solution. Your solution to this issue, which is still an issue in April 2024, is referenced with other information here on SO:
https://stackoverflow.com/a/77748425/161816

**Comment by harlam357** [comment]
Still an issue with v8.0.1. I used @dougcunha woff file workaround.

**Comment by Jamie-Clayton** [comment]
fixed in https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2217

**Comment by Alirexaa** [comment]
closed this as completed via  #2217
