### ISSUE TITLE
Allow to use relative address in Uri

### ISSUE THREAD

**Issue by cilerler** [Xabaril/AspNetCore.Diagnostics.HealthChecks#38]
As you may see below, serving address may change depends on environment. 
Unfortunately adding multiple references and/or changing it constantly is not a pleased workaround.

It would be convenient to have an option to use relative address in `Uri` like we can in **launchSettings.json**'s `launchUrl` property.

## appsettings.json

```json
"HealthChecks-UI": {
	"HealthChecks": [
		{
			"Name": "Self",
			"Uri": "http://localhost:47920/health/beatpulse"
		}
	]
}
```

## launchSettings.json
```
{
	"iisSettings": {
		"windowsAuthentication": false,
		"anonymousAuthentication": true,
		"iisExpress": {
			"applicationUrl": "http://localhost:47920/",
			"sslPort": 0
		}
	},
	"$schema": "http://json.schemastore.org/launchsettings.json",
	"profiles": {
		"IIS Express": {
			"commandName": "IISExpress",
			"launchBrowser": true,
			"launchUrl": "health/beatpulse-ui",
			"environmentVariables": {
				"ASPNETCORE_ENVIRONMENT": "Development"
			}
		},
		"MyProject.Api": {
			"commandName": "Project",
			"launchBrowser": true,
			"launchUrl": "health/beatpulse-ui",
			"environmentVariables": {
				"ASPNETCORE_ENVIRONMENT": "Development"
			},
			"applicationUrl": "https://localhost:47923/;http://localhost:47922/"
		},
		"Docker": {
			"commandName": "Docker",
			"launchBrowser": true,
			"launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/api/values"
		  }
	}
}
```

**Comment by CarlosLanderas** [comment]
@cilerler this scenario might be only supported when you are configuring the UI on the same place as the HealthChecks. It that you use case? For separate hosts the relative Uri would not be valid.

**Comment by cilerler** [comment]
correct

**Comment by CarlosLanderas** [comment]
@cilerler I was working on other feature but will try to implement this soon :)

**Comment by CarlosLanderas** [comment]
@cilerler  using the server feature `IServerAddressesFeature` we can get the configured urls when using **Kestrel** without problems to allow relative urls in settings but I am not really sure if we can do that when using **IIS**.

Like this is happening on startup and we do not have an active request we can just relay on information provided by the server and when using this feature IIS returns null.

@unaizorrilla  any idea?.

**Comment by cilerler** [comment]
@CarlosLanderas I found this https://github.com/aspnet/Announcements/issues/224

> Our servers have been updated in https://github.com/aspnet/HttpSysServer/issues/297 and https://github.com/aspnet/HttpSysServer/issues/297 so if Kestrel or HttpSysServer is being used, no changes are required. 
>
> If you are implementing a server and rely on the `IServerAddressesFeature` to be set by hosting, that will no longer be set and a default should be added when no address is configured. As an example:
>
>```c#
>var serverFeatures = featureCollection.Get<IServerAddressesFeature>();
>if (serverFeatures .Addresses.Count == 0)
>{
>    ListenOn(DefaultAddress); // Start the server on the default address
>   serverFeatures.Addresses.Add(DefaultAddress) // Add the default address to the IServerAddressesFeature
> }
>```
>
> Note that for Kestrel and HttpSysServer, the priority for address resolution is 
>1. Direct configuration via `KestrelServerOptions.Listen()` or `HttpSysOptions.UrlPrefixes.Add()`
>2. List of addresses in `IServerAddressesFeature.Addresses`
>3. Default address chosen by the server
>
> _Originally posted by @JunTaoLuo in https://github.com/aspnet/Hosting/issues/956#issuecomment-284036871_

**Comment by unaizorrilla** [comment]
Hi @CarlosLanderas any update on this issue?

**Comment by RaminderRandhawa91** [comment]
Hi, is this feature released ? 
I am also looking into adding relative url for uri in appSettings.json.

Thanks in advance!

**Comment by kogratte** [comment]
Hi!

I'm facing something close! We're hosting our application behind IIS and AspNetCore module. The server does not known his own Uri, so when HealthChecks-ui is trying to load the healtz data, he just get a 404.

**Comment by auserx** [comment]
any news on this?

**Comment by dsschneidermann** [comment]
If a feature is difficult for this, could we have an override possible in AspNetCore.Diagnostics.HealthChecks/src/HealthChecks.UI/Configuration/Options.cs?

Then we can read the port manually and create the correct uri string from outside.

**Comment by CarlosLanderas** [comment]
If you are looking to add remote host URIs programmatically this was added to the setupSettings Action in AddHealthChecksUI. The settings have two methods:

AddRemoteEndpoint(name, uri)
AddWebhookNotification(name, Uri..)

**Comment by cilerler** [comment]
@CarlosLanderas somewhat confused, is this issue has been resolved?

**Comment by CarlosLanderas** [comment]
@cilerler , you can follow the issue here, where we threw the question to asp.net team members:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/279

**Comment by hyha** [comment]
Probably this is not yet completely fixed, if relative URL is used, you will still face error on UI(browser side) with error "Only 'http' and 'https' schemes are allowed"

**Comment by CarlosLanderas** [comment]
endpoints.MapHealthchecks if from Microsoft. Can you try using /health-status please (with slash)

**Comment by CarlosLanderas** [comment]
Can you show the health Checks that you are configuring?  I am using the same config and it works. Might be a Uri for one of the healthchecks

**Comment by hyha** [comment]
Sorry missed that part...

![image](https://user-images.githubusercontent.com/1532980/71194304-b312aa00-2259-11ea-8563-f8453adcda36.png)

Just plain AddHealthCheckUI() as its configured in appsettings.json

**Comment by CarlosLanderas** [comment]
Those are your errors. You are using ---- as connection strings and most libraries parse the connection strings. Use real or valid ones to get rid of the error

**Comment by CarlosLanderas** [comment]
Are you sure the connection strings are valid? It looks the error might come from there.

**Comment by hyha** [comment]
Thanks a lot for your time!
I'm using Kestrel, on MacOS 10.15.2 with dotnet sdk 3.1.100.
I've pasted skeleton code to https://github.com/hyha/healthchecksample
![image](https://user-images.githubusercontent.com/1532980/71205476-7ef6b380-2270-11ea-9156-e27e9189f131.png)

**Comment by CarlosLanderas** [comment]
@hyha, this is working nice using Windows and Linux but I do not have a macOS to test. Could you test the following please?


Try to configure your scenario in one of the samples in this solution. This one for example:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/master/samples/HealthChecks.UI.Branding

Then I would need to to set a breakpoint in the following line:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI/Core/ServerAddressesService.cs#L27

Maybe the reported server addresses in macOS are different and the first being grabbed is not a valid http/https address.

If you can show me what is resolved there it would be really helpful.

Thanks

**Comment by hyha** [comment]
Thanks Carlos, running that example did stopped at break point, where:
input argument (relativeUrl) = "status/200?code=ax3rt56s"
AddressesFeature.Addresses = 
[0] [string]:"http://localhost:5000"
[1] [string]:"https://localhost:5001"

**Comment by CarlosLanderas** [comment]
this makes no sense. The reported uris are correct http/https urls. Please, use the whole url in healthchecks appsettings:

 http://localhost:5000/health-status

 to discard is not a connection string healthcheck error

**Comment by hyha** [comment]
absoluteUri = {file:///health-random}
![image](https://user-images.githubusercontent.com/1532980/71257003-82398000-2300-11ea-8d66-48cb4037b3ca.png)

Yesterday I was using "full URL" in config or code it was working, but the moment I switch to relative this L88 will complain about URL scheme not valid, also same error message on UI after launch.

**Comment by hyha** [comment]
I think there's an issue on L107 (GetEndpointUri), where "Uri.TryCreate" with Uri="/health-random" & UriKind.Absolute is returning **true**....

![image](https://user-images.githubusercontent.com/1532980/71257391-a053b000-2301-11ea-99bc-b175012bfd71.png)

**Comment by CarlosLanderas** [comment]
```csharp
var created = Uri.TryCreate("/health-random", UriKind.Absolute, out var uri);
```
Are this the values? This is an obvious false for me. Weird

**Comment by hyha** [comment]
![image](https://user-images.githubusercontent.com/1532980/71257580-0dffdc00-2302-11ea-835d-bfca0d450b7f.png)

**Comment by CarlosLanderas** [comment]
It looks like this:

https://github.com/dotnet/corefx/issues/22098

**Comment by hyha** [comment]
> It looks like this:
> 
> [dotnet/corefx#22098](https://github.com/dotnet/corefx/issues/22098)
> 
> To be exact:
> 
> [dotnet/corefx#22098 (comment)](https://github.com/dotnet/corefx/issues/22098#issuecomment-528903715)

Yup, seems like to make this work may need some uglier string operations...

**Comment by CarlosLanderas** [comment]
@hyha , can you try this on line 109:

if (!parsedUri || absoluteUri.IsFile)

**Comment by CarlosLanderas** [comment]
@hyha can you try this in line 109:

```csharp
if (!parsedUri || absoluteUri.Scheme != "http" && absoluteUri.Scheme != "https") || absoluteUri.IsFile)
```

**Comment by hyha** [comment]
![image](https://user-images.githubusercontent.com/1532980/71258771-fa09a980-2304-11ea-988c-d860271c8610.png)
That works too

**Comment by CarlosLanderas** [comment]
@hyha, I have been able to reproduce this problem with Manjaro Linux. Could you try this branch to confirm and I submit a PR?

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/unix-absolute-paths-fix

**Comment by CarlosLanderas** [comment]
@hyha I was able to reproduce the issue with Manjaro Linux. Can you test with branch to confirm it works for you?

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/unix-absolute-paths-fix

**Comment by hyha** [comment]
This is fixed, thanks a lot @CarlosLanderas

**Comment by hyha** [comment]
Hope we can have this released to test in real environments

**Comment by CarlosLanderas** [comment]
Thanks to you for reporting it! I'll release it today.
