### ISSUE TITLE
[UI] Relative Address for HealthCheckEndpoint with Kestrel at http://0.0.0.0:0

### ISSUE THREAD

**Issue by Genmutant** [Xabaril/AspNetCore.Diagnostics.HealthChecks#410]
I'm trying to bind HealthCheckEndpoint using the relative address;

```
services.AddHealthChecksUI(setupSettings: settings => settings.AddHealthCheckEndpoint("ABC", "/health"));
```

but because it is configured to use http://0.0.0.0:0 in Kestrel, it throws an exception. I'm not hard set on using automatic port selection, though it is nice for testing. It throws the same exception when using a specific port, though.

```
2020-02-07 10:37:31.3948|WARN|Microsoft.AspNetCore.Server.Kestrel|Overriding address(es) 'https://localhost:5001'. Binding to endpoints defined in UseKestrel() instead.|
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://0.0.0.0:51713
2020-02-07 10:37:31.5178|INFO|Microsoft.Hosting.Lifetime|Now listening on: http://0.0.0.0:51713|
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://0.0.0.0:51714
2020-02-07 10:37:31.5178|INFO|Microsoft.Hosting.Lifetime|Now listening on: https://0.0.0.0:51714|
fail: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
      GetHealthReport threw an exception when trying to get report from /health configured with name TransactionServer.
System.Net.Http.HttpRequestException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. (Parameter 'hostName')
 ---> System.ArgumentException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. (Parameter 'hostName')
   at System.Net.Dns.HostResolutionBeginHelper(String hostName, Boolean justReturnParsedIp, Boolean throwOnIIPAny, AsyncCallback requestCallback, Object state)
   at System.Net.Dns.BeginGetHostAddresses(String hostNameOrAddress, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.MultipleConnectAsync.StartConnectAsync(SocketAsyncEventArgs args, DnsEndPoint endPoint)
   at System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)
2020-02-07 10:37:32.3037|ERROR|HealthChecks.UI.Core.HostedService.HealthCheckReportCollector|GetHealthReport threw an exception when trying to get report from /health configured with name TransactionServer.|System.Net.Http.HttpRequestException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. (Parameter 'hostName')
 ---> System.ArgumentException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. (Parameter 'hostName')
   at System.Net.Dns.HostResolutionBeginHelper(String hostName, Boolean justReturnParsedIp, Boolean throwOnIIPAny, AsyncCallback requestCallback, Object state)
   at System.Net.Dns.BeginGetHostAddresses(String hostNameOrAddress, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.MultipleConnectAsync.StartConnectAsync(SocketAsyncEventArgs args, DnsEndPoint endPoint)
   at System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration)
```

**Comment by tidusjar** [comment]
I'm having the same issue as this, did you find a solution?

**Comment by ildoc** [comment]
i've got the same error in appsettings.json

```
"HealthChecks-UI": {
    "HealthChecks": [
      {
        "Name": "MySelf",
        "Uri": "/hc"
      },
    [...]
```

**Comment by CarlosLanderas** [comment]
@Genmutant  @tidusjar  @ildoc , What operative system are you using?

**Comment by ildoc** [comment]
I'm running my app from a linux docker container with all the kestrel default settings

**Comment by tidusjar** [comment]
I'm running on Windows, but this will apply to all OS's that net core supports.
Kestrel is listening on `http://*:5000`

You can repro this using my repo if you want, just pull the sln down (branch = `feature/v4`) and un-comment the following lines: https://github.com/tidusjar/Ombi/blob/feature/v4/src/Ombi/Startup.cs#L84

**Comment by CarlosLanderas** [comment]
0.0.0.0 for IPv4 represents kestrel listening on all ips, and [::] is the IpV6 equivalent. 
However the IServerAddressesFeature just reports the plain test configuration and not the final ips, so we can say this feature can only work when mapping relative services to localhost

If you receive something like: http://[::]:8001 from the server address feature we can't compose the final url.

I recommend you to setup the listerning urls in the docker container:

```csharp
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseUrls("http://localhost:5000")
            .UseStartup<Startup>();
```

in 3.X:

```csharp
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseUrls("http://localhost:5000")
            .UseStartup<Startup>();
```

**Comment by CarlosLanderas** [comment]
@rynowak any idea how can we use the IServerAddressFeature from AspNetcore to compose fully qualified urls from a relative path when kestrel is listening to all ips in ipv4/ ipv6?. Thanks!

**Comment by rynowak** [comment]
> @rynowak any idea how can we use the IServerAddressFeature from AspNetcore to compose fully qualified urls from a relative path when kestrel is listening to all ips in ipv4/ ipv6?. Thanks!

There's no real way to do it without some guesswork. The problem is that the server doesn't know and doesn't care what hostname/ip the request arrives on 😆 

Usually we avoid these problems in ASP.NET Core by using the hostname of the current request. That only helps if you have a request to use.

You could use something like `Dns.GetHostname()`. 

Or you could look at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#host-filtering which is something we recommend people use in production deployments.

**Comment by CarlosLanderas** [comment]
Thank you very much @rynowak :)

**Comment by CarlosLanderas** [comment]
@rynowak this is working with 0.0.0.0:0, and *:{port}

```csharp
        internal string AbsoluteUriFromRelative(string relativeUrl)
        {
            var targetAddress = AddressesFeature.Addresses.First();

            if (targetAddress.EndsWith("/"))
            {
                targetAddress = targetAddress[0..^1];
            }

            if (!relativeUrl.StartsWith("/"))
            {
                relativeUrl = $"/{relativeUrl}";
            }
            var hostCheck = Uri.CheckHostName(targetAddress);

            if(hostCheck == UriHostNameType.Unknown)
            {
                Uri.TryCreate(targetAddress, UriKind.Absolute, out var original);
                targetAddress = $"{original.Scheme}://{Dns.GetHostName()}:{original.Port}";
            }

            return $"{targetAddress}{relativeUrl}";
        }
```

**Comment by CarlosLanderas** [comment]
@rynowak this is working with 0.0.0.0:0 and *:{port}. Whenever the host name is not resolved as a dns name we resolve the hostname. Looks good?

```csharp
internal string AbsoluteUriFromRelative(string relativeUrl)
        {
            var targetAddress = AddressesFeature.Addresses.First();
            Uri.TryCreate(targetAddress, UriKind.Absolute, out var original);

            if (targetAddress.EndsWith("/"))
            {
                targetAddress = targetAddress[0..^1];
            }

            if (!relativeUrl.StartsWith("/"))
            {
                relativeUrl = $"/{relativeUrl}";
            }
            var hostCheck = Uri.CheckHostName(original.DnsSafeHost);

            if(hostCheck != UriHostNameType.Dns)
            {
                targetAddress = $"{original.Scheme}://{Dns.GetHostName()}:{original.Port}";
            }

            return $"{targetAddress}{relativeUrl}";
        }
```

**Comment by rynowak** [comment]
The code looks fine. The only concern that I'd have is that techniques like this aren't foolproof - there is no solution that is. 

Consider what would happen if this were deployed to k8s. Someone navigates to `http://health` (based on Service). You (using `Dns.GetHostName()` generate `http://health-dashboard-dkfkdfk-39393` (based on Pod name). Now all your URLs are affinitized to the pod that generated them- if that pod is shut down then those URLs don't work.

Again, there's no foolproof method you can use here without making the user configure it. You have to know what DNS names are in use by all of your clients - this isn't information the server can guess.

**Comment by CarlosLanderas** [comment]
Would it be better just using DNS names in kestrel configuration?

I always configure apps to localhost and never found this problem before but based on the feedback in this issue it looks like there are several people listening on all ips.

**Comment by rynowak** [comment]
> Would it be better just using DNS names in kestrel configuration?

What would this entail? Does that mean that the server has to `nslookup` to translate its IP to hostnames?  We're unlikely to build something like that in unless other features in .NET need it for something. We don't use the listening address for anything other than binding today (on purpose). 

The simple/safe thing to do is have the user configure the value.

 If you try to auto-configure it, I think you'll always run into cases that don't work "as expected" for someone/some configuration. Running nslookup yourself and using the results might be the closest you can come, but it sounds pretty complex (you have to list all of the IPs, then look them all up, then figure out which of the many hostnames it might return should be used).

**Comment by CarlosLanderas** [comment]
@ildoc  @tidusjar @Genmutant , based on @rynowak feedback, I suppose the best think you can do is configuring the listening ip in Kestrel and problem resolved. If you are using a docker image setting the listening address to localhost fixes the problem.

I agree this change "works", but might open new problems in then future while configuring the host ip / dns name is straightforward

**Comment by ignatandrei** [comment]
@rynowak  @CarlosLanderas 

What if we use this:

Host = Host.Replace("0.0.0.0", "localhost");
 Host = Host.Replace("[::]", "localhost");
            
?

**Comment by NicolasREY69330** [comment]
@CarlosLanderas 👍 
Could you provide any sample from a docker / docker compose perspective to ensure we do it the right way please ?

**Comment by edumserrano** [comment]
I would also appreciate some sample to understand how to run in docker/docker compose. If you also could explain how to get it working in K8s it would be appreciated.

**Comment by NicolasReyDotNet** [comment]
@edumserrano @CarlosLanderas 
Hi, any update on this ?

**Comment by edumserrano** [comment]
> @edumserrano @CarlosLanderas
> Hi, any update on this ?

I didn't find any solution. I just use an absolute url.

**Comment by ignatandrei** [comment]
What about my previous suggestion?

**Comment by NicolasReyDotNet** [comment]
@edumserrano 
You work with a dockercompose file ? If yes I'm interested in seeing it and you startup.cs file as well, could you share these piece of code here ?

**Comment by MikeChristensen** [comment]
I ran into this same problem today, and here's the solution I came up with.  Basically, I create an extension method on `IWebHostBuilder` which takes the URLs, normalizes them (replaces `0.0.0.0` or `*` with `localhost`) and creates the healthcheck endpoints:

```
internal static class HealthCheckConfigurationExtensions
{
    /// <summary> Normalize an enumeration of URLs to "localhost" if wildcard bindings are used </summary>
    private static IEnumerable<string> Normalize(this IEnumerable<string> urls) =>
        urls.Select(url => Regex.Replace(url, @"^(?<scheme>https?):\/\/((\*)|(0.0.0.0))(?=[\:\/]|$)", "${scheme}://localhost"));
    public static IWebHostBuilder ConfigureHealthcheck(this IWebHostBuilder host, params string[] urls)
    {
        host.ConfigureServices(serviceBuilder =>
        {
            serviceBuilder
                .AddHealthChecksUI(setupSettings =>
                {
                    var uris = urls.Normalize().Select(uri => new Uri(uri, UriKind.Absolute)).ToArray();
                    var httpEndpoint = uris.FirstOrDefault(uri => uri.Scheme == "http");
                    var httpsEndpoint = uris.FirstOrDefault(uri => uri.Scheme == "https");
                    if (httpEndpoint != null) // Create an HTTP healthcheck endpoint
                    {
                        setupSettings.AddHealthCheckEndpoint("HTTP", new UriBuilder(httpEndpoint.Scheme, httpEndpoint.Host, httpEndpoint.Port, "/health.json").ToString());
                    }
                    if (httpsEndpoint != null) // Create an HTTPS healthcheck endpoint
                    {
                        setupSettings.AddHealthCheckEndpoint("SSL", new UriBuilder(httpsEndpoint.Scheme, httpsEndpoint.Host, httpsEndpoint.Port, "/health.json").ToString());
                    }
                });
        });
        return host;
    }
}
```

Now, when I build my `IWebHost`, I can configure the healthchecks as well:

```
var host = new WebHostBuilder()
    .UseKestrel()
    .UseConfiguration(localConfig)
    .UseContentRoot(Directory.GetCurrentDirectory())
    .ConfigureServices(serviceBuilders)
    .Configure(appBuilders)
    .ConfigureHealthcheck(urls) // <--- Extension method
    .UseUrls(urls);
```

It would also be possible to combine `ConfigureHealthcheck` and `UseUrls` into a single extension method that does both of those things.

In my case, I'm adding a healthcheck for the first HTTP binding and the first HTTPS binding found, but your situation might be different and you can adjust the code.

Hope this helps someone!

**Comment by maikebing** [comment]
@MikeChristensen Thank you very much，I modified the regular expression
`^(?<scheme>https?):\/\/((\*)|(0.0.0.0))(?=[\:\/]|$)`
`^(?<scheme>https?):\/\/((\+)|(\*)|(0.0.0.0))(?=[\:\/]|$)`

```
  var urls = Environment.GetEnvironmentVariable("ASPNETCORE_URLS").Split(';');
                var uris = urls.Select(url => Regex.Replace(url, @"^(?<scheme>https?):\/\/((\+)|(\*)|(0.0.0.0))(?=[\:\/]|$)", "${scheme}://localhost"))
                                .Select(uri => new Uri(uri, UriKind.Absolute)).ToArray();
                var httpEndpoint = uris.FirstOrDefault(uri => uri.Scheme == "http");
                var httpsEndpoint = uris.FirstOrDefault(uri => uri.Scheme == "https");
                if (httpEndpoint != null) // Create an HTTP healthcheck endpoint
                {
                    setup.AddHealthCheckEndpoint("IoTSharp HTTP", new UriBuilder(httpEndpoint.Scheme, httpEndpoint.Host, httpEndpoint.Port, "/healthz").ToString());
                }
                if (httpsEndpoint != null) // Create an HTTPS healthcheck endpoint
                {
                    setup.AddHealthCheckEndpoint("IoTSharp SSL", new UriBuilder(httpsEndpoint.Scheme, httpsEndpoint.Host, httpsEndpoint.Port, "/healthz").ToString());
                }
                else
                {
                    //One endpoint is configured in appsettings, let's add another one programatically
                    setup.AddHealthCheckEndpoint("IoTSharp", "/healthz");
                }
```

**Comment by MaxThom** [comment]
Hi, I've been trying so many things to fix this issues. Ultimately, im trying to deploy on Azure WebApp for Linux Container, but for now i cant get it to work even on my local machine. Everything work except this. I tried settings env variable with urls: "http://localhost:80;https://localhost:443", but then even the index break. I tried to set absolute address on health endpoint, but without success. I changed Kestrel UseUrls to localhost, without success.

Any tips ?

**Comment by koimad** [comment]
Has anybody resolved this issue, I'm getting the same problems.

**Comment by SumitAngra** [comment]
Hi Everyone, 
Facing the same issue for the service fabric cluster.
Kindly do let me know if this is resolved or not.
Thanks

**Comment by michalkonieczny91** [comment]
To workaround the problem in containers you have to specify a single IP address for listening instead all 
To do this you can follow 
## k8s:
Use [downward API](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#the-downward-api) to get container IP (`MY_POD_IP`) using `status.podIP`, then use this `MY_POD_IP` into  `ASPNETCORE_URLS`  `"http://$(MY_POD_IP):80"` 
below piece of manifest 

```
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ASPNETCORE_URLS
              value: "http://$(MY_POD_IP):80"
```
## docker-compose:
you can use same trick but instead of using API you can use just linux `hostname` command 

```
    entrypoint: [ "/bin/sh","-c" ]
    command:
      - |
        sleep 60
        export ASPNETCORE_URLS="http://$$(hostname -i):80;https://$$(hostname -i):443"
        dotnet /app/.web-ui.dll
```
you have to overide entrypoint to invoke shell script from command 
and you can find a one liner 
`export ASPNETCORE_URLS="http://$$(hostname -i):80;https://$$(hostname -i):443"`

A `$$(hostname -i)` statement is get container IP and the double `$$` is for escape

Hope it will help :)

**Comment by RyanSearle** [comment]
The whole UI feature is unusable when using Kestrel with a dynamic port.

If HealthChecks.UI.Configuration.Settings allowed me to provide the BaseAddress for the HttpClient with a delegate which supplies the IServiceProvider I could dynamically add the port before each request.

Why does the port need to be known upfront?

BTW it looks like ConfigureApiEndpointHttpclient should do this however changing the BaseAddress does nothing.

**Comment by bayramerenn** [comment]
i had the same problem. Can you share an example so I can solve it?

**Comment by RyanSearle** [comment]
I've forked the repo with the required change https://github.com/RyanSearle/AspNetCore.Diagnostics.HealthChecks.

You'll just need to build it and use the package.

Alternatily look at the first commit and make the change yourself.

**Comment by alsami** [comment]
> I've forked the repo with the required change https://github.com/RyanSearle/AspNetCore.Diagnostics.HealthChecks.
> 
> You'll just need to build it and use the package.
> 
> Alternatily look at the first commit and make the change yourself.

Why is this ticket closed, when the solution to this is as simple as visible in the fork? Is there something else to consider with this fix?
I am happy to send in a PR if that helps.

**Comment by alsami** [comment]
Are there any other use-cases to use the loop-back address that I am not aware of? AFAIK it can always only be localhost but I might be wrong here as well :)

**Comment by RyanSearle** [comment]
So 127.0.0.1 will always be the loopback address and machines tend to resolve localhost to it. The problem is that 0.0.0.0 could be used for other purposes by other systems so that's where the problem is.

**Comment by ignatandrei** [comment]
Could we put a config for this?

**Comment by Floyddotnet** [comment]
this solution works for me: `settings.AddHealthCheckEndpoint("Healthchecks", "http://localhost:8999/healthz")`

**Comment by guilhermelouzavio** [comment]
Ao tentar a solução dada pelo @alexpejoch obtenho esse erro , alguma sugestão?
![16868792118503785226150649073089](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/14909933/8006ec78-9d49-457d-9b09-b981f9f89c04)

**Comment by sungam3r** [comment]
Please see https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/1593#issuecomment-1617522623 . If after the publication of the v7 release you will still observe problems, then please open new issue.

**Comment by SkinnySackboy** [comment]
@sungam3r This is unfortunately still an issue for us out of the box, with our Linux deployment.

**Comment by flookami** [comment]
### Still the issue in V7.0.2

To reproduce the issue: 
- create a basic aspnet core API 
- make sure you use Listen Any Ip (= listen on all network interfaces = 0.0.0.0)

```

using HealthChecks.UI.Client;
using Microsoft.AspNetCore.Diagnostics.HealthChecks;
using System.Net;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.WebHost.ConfigureKestrel(options =>
{
     **options.Listen(IPAddress.Any, 8080);**
});

builder.Services.AddHealthChecks();

builder.Services.AddHealthChecksUI(opt =>
{
    opt.AddHealthCheckEndpoint(name: "HEALTH ENDPOINT", uri: "/healthz");
}).AddInMemoryStorage();

var app = builder.Build();

// Configure the HTTP request pipeline.
app.MapHealthChecks(pattern: "/healthz", options: new HealthCheckOptions
{
    Predicate = _ => true,
    ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
});

app.MapHealthChecksUI();
app.Run();

```

LOGS:

> info: System.Net.Http.HttpClient.health-checks.ClientHandler[100]
>       Sending HTTP request GET http://0.0.0.0:8080/healthz
> info: Microsoft.Hosting.Lifetime[0]
>       Application started. Press Ctrl+C to shut down.
> info: Microsoft.Hosting.Lifetime[0]
>       Hosting environment: Development
> info: Microsoft.Hosting.Lifetime[0]
>       Content root path: C:\Users\mhett\source\repos\HealthChecksTests\HealthChecksTests
> fail: **HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]
>       GetHealthReport threw an exception when trying to get report from /healthz configured with name API.
>       System.Net.Http.HttpRequestException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. (Parameter 'hostName') (0.0.0.0:8080)**

**Comment by orknist** [comment]
If you have Docker profile in your launchSettings.json file like;
```
"Docker": {
  "commandName": "Docker",
  "launchBrowser": true,
  "environmentVariables": {
    "ASPNETCORE_HTTPS_PORTS": "8081",
    "ASPNETCORE_HTTP_PORTS": "8080"
  },
  "publishAllPorts": true,
  "useSSL": true
}
```

just add endpoint like that;
```
var urls = Environment.GetEnvironmentVariable("ASPNETCORE_URLS");
var endpoint = string.IsNullOrEmpty(urls) ? "http://localhost:8080" : urls.Split(';').First();
builder.Services.AddHealthChecksUI(setup =>
{
    setup.AddHealthCheckEndpoint("HealthChecks", $"{endpoint}/health");
}).AddInMemoryStorage();
```

The backend api service of HealthCheckUI, which gets the data from the target, is already running inside the docker. Therefore, when localhost is used as the address, the code will work because the request will go to the docker container that contains it.

**Comment by VAllens** [comment]
I'm having the same problem.
My program is running locally on windows and it's listening at `https://[::]:5050`.
I'm using is `AspNetCore.HealthChecks.UI` v8.0.1.

Below is my code:
```csharp
services.AddHealthChecksUI(settings =>
	{
		settings.AddHealthCheckEndpoint("feedback api", "/api/health");
		//other settings...
	})
	.AddInMemoryStorage();
```

**Comment by whichatao** [comment]
I'm getting the same problems. 
```
services.AddHealthChecksUI(setup =>
  {
      setup.AddHealthCheckEndpoint($"Health Check", "/healthz");
  }).AddInMemoryStorage();
```

change to:

```
  services.AddHealthChecksUI(setup =>
  {
      setup.AddHealthCheckEndpoint($"Health Check", "https://www.mydomain.com/healthz");
  }).AddInMemoryStorage();
```

resolved.

**Comment by HristoYankovTR** [comment]
It's Jan-2025 and we still can't configure the UI to use a relative URL, lol.

**Comment by RSReswin** [comment]
Question in Feb 7, 2020 still not get answer in 2025.

**Comment by RSReswin** [comment]
```
fail: HealthChecks.UI.Core.HostedService.HealthCheckReportCollector[0]

      GetHealthReport threw an exception when trying to get report from [http://OnlySwipe-API:8000/healthz⁠](http://onlyswipe-api:8000/healthz) configured with name OnlySwipe-API.

      System.Net.Http.HttpRequestException: Connection refused (onlyswipe-api:8000)

       ---> System.Net.Sockets.SocketException (111): Connection refused

         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)

         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)

         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)

         --- End of inner exception stack trace ---

         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

         at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)

         at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReport(HealthCheckConfiguration configuration) in /src/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs:line 101
```

i also get this error, i run this HealthCheckUi and all my service inside docker container and i am using aspire and build my application using aspirate and aspirate generate the docker-compose.yaml file, using that file i deploy my application in docker and i get this error in HealthCheckUi container.

and i fix this issue like this, aspirate auto generated docker-compose.yaml have like this endpoint.

```yaml
  HealthCheck:
    container_name: "HealthCheck"
    image: "docker.io/xabarilcoding/healthchecksui:latest"
    environment:
      ui_path: "/"
      HealthChecksUI__HealthChecks__0__Name: "OnlySwipe-API"
      HealthChecksUI__HealthChecks__0__Uri: "OnlySwipe-API:8000/healthz" //this line is the issue
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18888"
      OTEL_SERVICE_NAME: "HealthCheck"
    ports:
    - target: 80
      published: 8108
```

and i change it to this.

```yaml
  HealthCheck:
    container_name: "HealthCheck"
    image: "docker.io/xabarilcoding/healthchecksui:latest"
    environment:
      ui_path: "/"
      HealthChecksUI__HealthChecks__0__Name: "OnlySwipe-API"
      HealthChecksUI__HealthChecks__0__Uri: "http://OnlySwipe-API:8000/healthz" //issue fixed
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18888"
      OTEL_SERVICE_NAME: "HealthCheck"
    ports:
    - target: 80
      published: 8108
```

i thought when run the application inside docker it i will automatically take the http:// but it is not taking like that.

**Comment by ophilippov** [comment]
If anybody is still facing this issue, here is what you can do. 

1. Create a delegating handler that would redirect all requests to localhost, something like:
```csharp
internal class LocalhostRedirectHandler : DelegatingHandler
{
  protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  {
    var uri = request.RequestUri;
    if (uri is null) return base.SendAsync(request, cancellationToken);

    // If URI resolved against 0.0.0.0 or [::], or any other wildcard - then rewrite to loopback, keep scheme+port
    if (uri.Host is "0.0.0.0" or "[::]" or "::" or "*" or "+")
      request.RequestUri = new UriBuilder(uri) { Host = "localhost" }.Uri;

    return base.SendAsync(request, cancellationToken);
  }
}
```
2. Register this handler in DI as transient:
`services.AddTransient<LocalhostRedirectHandler>();`
3. Make the health check UI use this handler:
```csharp
services
      .AddHealthChecksUI(options =>
      {
        options.AddHealthCheckEndpoint("Your app name", "/health");
        options.UseApiEndpointDelegatingHandler<LocalhostRedirectHandler>();
        options.SetEvaluationTimeInSeconds(10);
        options.SetApiMaxActiveRequests(1);
      })
    .AddInMemoryStorage();
```

Now, regardless of the url configuration, ports, etc., all requests from the health check UI will be redirected to localhost, while preserving the scheme and port.

**Comment by RedEye-Developers** [comment]
> If anybody is still facing this issue, here is what you can do.
> 
> 1. Create a delegating handler that would redirect all requests to localhost, something like:
> 
> internal class LocalhostRedirectHandler : DelegatingHandler
> {
>   protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>   {
>     var uri = request.RequestUri;
>     if (uri is null) return base.SendAsync(request, cancellationToken);
> 
>     // If URI resolved against 0.0.0.0 or [::], or any other wildcard - then rewrite to loopback, keep scheme+port
>     if (uri.Host is "0.0.0.0" or "[::]" or "::" or "*" or "+")
>       request.RequestUri = new UriBuilder(uri) { Host = "localhost" }.Uri;
> 
>     return base.SendAsync(request, cancellationToken);
>   }
> }
> 2. Register this handler in DI as transient:
>    `services.AddTransient<LocalhostRedirectHandler>();`
> 3. Make the health check UI use this handler:
> 
> services
>       .AddHealthChecksUI(options =>
>       {
>         options.AddHealthCheckEndpoint("Your app name", "/health");
>         options.UseApiEndpointDelegatingHandler<LocalhostRedirectHandler>();
>         options.SetEvaluationTimeInSeconds(10);
>         options.SetApiMaxActiveRequests(1);
>       })
>     .AddInMemoryStorage();
> Now, regardless of the url configuration, ports, etc., all requests from the health check UI will be redirected to localhost, while preserving the scheme and port.

thanks.
