### ISSUE TITLE
HealthCheckReportCollector stop collecting if an endpoint returns an empty response

### ISSUE THREAD

**Issue by shessane** [Xabaril/AspNetCore.Diagnostics.HealthChecks#92]
In the HealthCheckReportCollector class, the [GetHealthReport ](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/2.2.0-upgrade-uri-2.2.2/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs#L83) method uses the [As](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI/Core/Extensions/HttpResponseMessageExtensions.cs#L15) extension method to deserialize an UIHealthReport.
This will use the NewtonSoft JsonConvert.DeserializeObject that return a null object if content is empty. Wich leads to an [unhandled NullReferenceException](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/2.2.0-upgrade-uri-2.2.2/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs#L57) that **stop the Collect loop**.

A quick fix will be to throw an exception if the response content is empty. This exception will be correctly catched in GetHealthReport.

**Comment by unaizorrilla** [comment]
Hi,

I need to review this, thanks for fill the issue

**Comment by unaizorrilla** [comment]
Fixed on  1772eea . A new package will be published on NuGet ( version 2.2.11 for UI ) when the release build finish.

Thanks @shessane  for fill the issue, please close this if new package solve it.

**Comment by shessane** [comment]
Thank you @unaizorrilla for the fix, but the problem is not solved.
Empty strings content deserialize as null object. I've discovered that whitspaces also deserialize as null object.

I think the best is to check the returned object instead of checking for empty strings as I suggested before :

```c#
var result = JsonConvert.DeserializeObject<TContent>(content);

if (result != null) return result;

throw new InvalidOperationException($"Response is null or message can't be deserialized as {typeof(TContent).FullName}.");
```

Sorry for this

**Comment by unaizorrilla** [comment]
On appveyor, package 2.2.12 version when build finished

**Comment by shessane** [comment]
Thanks
